#!/bin/python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SAO_Login(object):
    def setupUi(self, SAO_Login):
        SAO_Login.setObjectName("SAO_Login")
        SAO_Login.setEnabled(True)
        SAO_Login.resize(400, 135)
        SAO_Login.setWindowTitle("Sword Art Online Login")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("7205445111595501398.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SAO_Login.setWindowIcon(icon)
        SAO_Login.setStyleSheet("background-color: rgb(0, 142, 252);\n"
"opacity:25%;")
        SAO_Login.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhSensitiveData)
        self.label = QtWidgets.QLabel(SAO_Login)
        self.label.setGeometry(QtCore.QRect(0, 0, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SAO_Login)
        self.label_2.setGeometry(QtCore.QRect(80, 20, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255,255,255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(SAO_Login)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255,255,255);")
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(SAO_Login)
        self.lineEdit.setGeometry(QtCore.QRect(80, 90, 251, 25))
        self.lineEdit.setStyleSheet("background-color:none;\n"
"border-style:offset;")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(SAO_Login)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 40, 251, 25))
        self.lineEdit_2.setStyleSheet("background-color:none;\n"
"border-style:offset;")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(SAO_Login)
        QtCore.QMetaObject.connectSlotsByName(SAO_Login)

    def retranslateUi(self, SAO_Login):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("SAO_Login", "Log In_:: "))
        self.label_2.setText(_translate("SAO_Login", ":account"))
        self.label_3.setText(_translate("SAO_Login", ":password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SAO_Login = QtWidgets.QWidget()
    ui = Ui_SAO_Login()
    ui.setupUi(SAO_Login)
    SAO_Login.show()
    sys.exit(app.exec_())
